# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Atheist
email: scott_baron@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Dedicated to the dissemination of rational thought, thereby dispelling
  rumor, myth, conjucture and speculation.  
baseurl: "/a/" # the subpath of your site, e.g. /blog
url: "http://scottbaron.github.io" # the base hostname & protocol for your site
twitter_username: scottbaron
github_username:  scottbaron

# Build settings
markdown: kramdown
